# Generated by Django 5.0.4 on 2024-04-24 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('role', models.CharField(choices=[('Pilot', 'Pilot'), ('FlightAttendant', 'Flight Attendant'), ('Security Personnel', 'Security Personnel'), ('Air Traffic Controllers', 'Air Traffic Controllers'), ('Maintenance Crew', 'Maintenance Crew'), ('Customer Service Representatives', 'Customer Service Representatives')], default='Other', max_length=55)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.department')),
                ('staff_groups', models.ManyToManyField(blank=True, related_name='staff_groups', to='auth.group')),
                ('staff_user_permissions', models.ManyToManyField(blank=True, related_name='staff_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='staff.staff')),
                ('type_ratings', models.CharField(max_length=100)),
            ],
        ),
    ]
