# Generated by Django 5.0.4 on 2024-04-24 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='pilots',
            field=models.ManyToManyField(related_name='piloted_flights', to='staff.pilot'),
        ),
        migrations.AddField(
            model_name='flightstop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.city'),
        ),
        migrations.AddField(
            model_name='flightstop',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.flight'),
        ),
        migrations.AlterUniqueTogether(
            name='flightstop',
            unique_together={('flight', 'sequence')},
        ),
    ]
