# Generated by Django 5.0.4 on 2024-04-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_city_code_alter_flight_destination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city_name',
        ),
    ]
